### ISSUE TITLE
Investigate CDR (serialization)

### ISSUE THREAD

**Issue by gerkey** [osrf/ros_dds#11]
DDS uses the OMG Common Data Representation (CDR) to serialize data.  CDR is defined in Section 9.3 of [the CORBA v3.2 spec](http://www.omg.org/spec/CORBA/3.2/Interoperability/PDF).

Characterize the serialization format, specifically with respect to bandwidth and encoding/decoding efficiency.

**Comment by tfoote** [comment]
Closing this before archiving
