### ISSUE TITLE
Prototype

### ISSUE THREAD

**Issue by dirk-thomas** [osrf/ros_dds#13]
Tasks:
- [x] msg to idl generator (`genidl`)
- [x] idl to code generator, only c++ for now (`genidlcpp`)
- [x] conversion functions between dds and ros message instances
- [x] resolve relevant DDS types for a specific ROS message only based on its type
- [x] support services with `genidl` and `genidlcpp`

Issues:
- [ ] only the last message is actually sent when `publish()` is called multiple times without sleeping
- [ ] services use the same topic for all clients to send responses (since creating the response publisher dynamically did not work reliably)

**Comment by tfoote** [comment]
Closing this before archiving
