### ISSUE TITLE
Build OpenSpliceDDS v6.4 from source, error on Unbuntu 15.04

### ISSUE THREAD

**Issue by pczzy** [osrf/ros_dds#29]
Compile OpenSplice from source follow the ros guide ,this link https://github.com/osrf/ros_dds

# Install build-time prerequisites, which on Linux are:
# (see http://www.prismtech.com/opensplice/opensplice-dds-community/building for the full list)
sudo apt-get install gawk flex bison perl
git clone https://github.com/osrf/opensplice.git
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/tmp/opensplice
make install
# Tell CMake to look there for CMake configuration files
export CMAKE_PREFIX_PATH=/tmp/opensplice:$CMAKE_PREFIX_PATH

and got the following errors.

 

/tmp/ccUyNA26.ltrans11.ltrans.o: In function `DRV_cpp_putarg':
<artificial>:(.text+0x4a5b): undefined reference to `define'
<artificial>:(.text+0x4a7c): undefined reference to `define'
<artificial>:(.text+0x4ae8): undefined reference to `define'
<artificial>:(.text+0x4b3b): undefined reference to `Ifile'
<artificial>:(.text+0x4b85): undefined reference to `undef'
/tmp/ccUyNA26.ltrans18.ltrans.o: In function `DRV_drive':
<artificial>:(.text+0x430c): undefined reference to `preprocess'
<artificial>:(.text+0x47e7): undefined reference to `preprocess_getc'
collect2: error: ld returned 1 exit status
/opt/opensplice/setup/makefiles/target-only.mak:92: recipe for target 'cppgen' failed
make[8]: *** [cppgen] Error 1
makefile:6: recipe for target 'all' failed
make[7]: *** [all] Error 2
make[6]: *** No rule to make target 'build_tools_stage', needed by 'odlpp'.  Stop.
makefile:6: recipe for target 'link' failed
make[5]: *** [link] Error 2
/opt/opensplice/setup/makefiles/subsystem.mak:11: recipe for target 'osplcore.ss_link' failed
make[4]: *** [osplcore.ss_link] Error 2
/opt/opensplice/setup/makefiles/subsystem.mak:11: recipe for target 'src.ss_link' failed
make[3]: *** [src.ss_link] Error 2

**Comment by dirk-thomas** [comment]
We are not actively working on this repository anymore since it only contains an early prototype of ROS 2. Most up-to-date information can be found: https://github.com/ros2/ros2/wiki

In your case it looks like you install OpenSplice to `tmp/opensplice` but there seems to be something under `/opt/opensplice`. Maybe you are mixing two different versions on your system and don't have a clean environment.

**Comment by pczzy** [comment]
Building going on after follow this reference http://ros2.xyz/blog/2015/09/16/building-opensplicedds-v6-4-on-ubuntu15-04/

**Comment by dirk-thomas** [comment]
Am I right to assume that you @pczzy are owning ros2.xyz? If that is the case it would be good if you could clarify that on the website / blog. Currently it does not contain any information about who is providing it and the might mislead users that the website is an official resource of ROS 2.

**Comment by j-rivero** [comment]
Just for reference, upstream bug: https://github.com/PrismTech/opensplice/issues/18

**Comment by pczzy** [comment]
@j-rivero I create ros2.xyz and it's not official site. the initial purpose of this site is share/collecting something about next generation ROS for robot fan or geek . I can make some clarifying if needed.

**Comment by wjwwood** [comment]
@pczzy It's fine to have the site and the blog, just put an about page which states what you're doing and why.
