### ISSUE TITLE
example  compilation failed

### ISSUE THREAD

**Issue by xuefengchang** [osrf/ros_dds#31]
When I try to compile the example in the ros_dds, which is a chat app, I get the error " Chatter.cpp:26:23: fatal error: ccpp_Chat.h: No such file or directory." It seems that ccpp_Chat.h does not existed. How can I solve this problem?

**Comment by dirk-thomas** [comment]
Please see the first line in the README: 743793b877c387e6a14de0a7b8e8c086e3ef792b

> This was an early prototype and is no longer in development. Current work is being done at https://github.com/ros2/ros2
