### ISSUE TITLE
Investigate configuration of DDS

### ISSUE THREAD

**Issue by gerkey** [osrf/ros_dds#5]
System configuration is a major concern.  With the large feature set in DDS comes much potential configuration complexity.  We want to know:
- How easy or hard is it configure DDS for the common cases (single machine, all machines on a LAN, LAN + remote machine via VPN or similar, etc.)?
- In the common cases, what kind of interface could we present to users?  E.g., right now we use a handful of environment variables (ROS_MASTER_URI, ROS_IP, etc.), whereas DDS (or at least OpenSplice) uses an [XML format](http://www.prismtech.com/download-documents/1331) (full details in Chapter 4 of that document).  Their default looks like [this](https://github.com/osrf/opensplice/blob/master/etc/ospl_sp_ddsi.xml).  Would users be expected to modify such XML?
- How portable is DDS configuration between implementations? @gbiggs [mentioned](http://lists.ros.org/pipermail/ros-users/2014-February/068186.html) that there's a common XML configuration spec that's been standardized; is that actually in use? 
- Add more to this list.

**Comment by tfoote** [comment]
Closing this before archiving
